### ISSUE TITLE
run is slow and some errors

### ISSUE THREAD

**Issue by Breezeqiuyu** [arunmallya/packnet#3]
Hello, thank you very much for sharing. But I ran into some problems while running your code. I would really appreciate it if you could help me.
1. I'm running

Python main. Py - mode eval - dataset cubs_cropped - loadname/home/qiuyu/packnet - master/checkpoints/csf_0,0.75, 75-1 _vgg16_0. 5 - nobias - nobn_1. Pt

In this code, the program appeared "killed" and then stopped running. I wonder if it was because of my computer configuration. I used i5 and gpu=2070. When you run this program, the computer gets really stuck.

2. I'm running
   @@@@
Bash run_all_baseline_finetuning. Sh

This code, the program is reporting an error,
Traceback (most recent call last):
File "main.py", line 393, in <module></module>
The main ()
File "main.py", line 377, in main
The save = True, savename = args. Save_prefix)
File "main.py", line 215, in train
Self. Do_epoch (epoch_idx, optimizer)
File "main.py", line 172, in do_epoch
For batch, label in TQDM (self.train_data_loader, desc='Epoch: %d '% (epoch_idx)):
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 / site - packages/TQDM _tqdm. Py", line 1017, in __iter__
For obj in iterable:
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 / site - packages/torch/utils/data/dataloader py", line 301, in __iter__
Return DataLoaderIter (self)
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 / site - packages/torch/utils/data/dataloader py", line 158, in __init__
Baron tart ()
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 / multiprocessing/process. Py", line 105, in the start
Self. _popen = self. _popen (self)
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 / multiprocessing/context. Py", line 223, in _Popen
Return _default_context. Get_context (). The Process. _Popen (process_obj)
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 / multiprocessing/context. Py", line 277, in _Popen
Return Popen (process_obj)
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 multiprocessing/popen_fork py", line 19, in __init__
Self. _launch (process_obj)
The File "/ home/qiuyu/anaconda3 / envs/pytorch/lib/python3.6 multiprocessing/popen_fork py", line 66, in _launch
The self. The pid = OS. The fork ()
OSError: [Errno 12] no allocate memory

What's the reason for this?
Looking forward to your reply. Thank you very much. @

**Comment by Breezeqiuyu** [comment]
@ @ @
